# Generated by Django 4.1.4 on 2023-02-05 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Kitap', 'verbose_name_plural': 'Kitaplar'},
        ),
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(default=1, editable=False, max_length=300),
            preserve_default=False,
        ),
    ]
