# Generated by Django 4.1.4 on 2023-02-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(editable=False, max_length=300, unique=True),
        ),
    ]
