# Generated by Django 4.1.4 on 2023-02-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='book', verbose_name='Kapak Fotoğrafı'),
        ),
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(editable=False, max_length=300),
        ),
    ]
